name: Deploy Next.js to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            cd /home/debian/cryptosite

            git fetch --all
            git reset --hard origin/main

            npm ci
            npm run build

            pm2 restart cryptosite || pm2 start npm --name cryptosite -- start
            pm2 save
