/**
 * Broker Database Seed Script
 * Story 3.8: 240+ Supported Brokers
 */

import { PrismaClient, BrokerAssetType, IntegrationStatus } from '@prisma/client';

const prisma = new PrismaClient();

interface BrokerSeed {
  name: string;
  displayName?: string;
  country?: string;
  region?: string;
  integrationStatus: IntegrationStatus;
  supportedAssets: BrokerAssetType[];
  logoUrl?: string;
  websiteUrl?: string;
  apiDocumentationUrl?: string;
  csvTemplateUrl?: string;
  description?: string;
  priority: number;
}

const brokers: BrokerSeed[] = [
  // ============================================================================
  // TIER 1 - HIGH PRIORITY (API Integration)
  // ============================================================================
  {
    name: 'Interactive Brokers',
    displayName: 'Interactive Brokers (IBKR)',
    country: 'US',
    region: 'Global',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.FUTURES, BrokerAssetType.FOREX, BrokerAssetType.OPTIONS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.interactivebrokers.com',
    apiDocumentationUrl: 'https://www.interactivebrokers.com/api/doc.html',
    description: 'Global broker with comprehensive API access for all asset classes',
    priority: 100,
  },
  {
    name: 'Tradovate',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.tradovate.com',
    apiDocumentationUrl: 'https://api.tradovate.com',
    description: 'Futures trading platform with modern API',
    priority: 95,
  },
  {
    name: 'TD Ameritrade',
    displayName: 'TD Ameritrade / Charles Schwab',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS, BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.tdameritrade.com',
    apiDocumentationUrl: 'https://developer.tdameritrade.com',
    description: 'Major US broker with thinkorswim platform',
    priority: 90,
  },
  {
    name: 'Alpaca',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://alpaca.markets',
    apiDocumentationUrl: 'https://alpaca.markets/docs',
    description: 'Commission-free API-first stock trading',
    priority: 85,
  },
  {
    name: 'TradeStation',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.FUTURES, BrokerAssetType.OPTIONS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.tradestation.com',
    apiDocumentationUrl: 'https://api.tradestation.com',
    description: 'Advanced trading platform with API access',
    priority: 80,
  },

  // ============================================================================
  // TIER 2 - MEDIUM PRIORITY (File Upload)
  // ============================================================================
  {
    name: 'MetaTrader 4',
    displayName: 'MetaTrader 4 (MT4)',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.metatrader4.com',
    description: 'Popular forex trading platform - CSV export supported',
    priority: 75,
  },
  {
    name: 'MetaTrader 5',
    displayName: 'MetaTrader 5 (MT5)',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.STOCKS, BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.metatrader5.com',
    description: 'Advanced multi-asset trading platform - CSV export supported',
    priority: 75,
  },
  {
    name: 'NinjaTrader',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FUTURES, BrokerAssetType.FOREX, BrokerAssetType.STOCKS],
    websiteUrl: 'https://ninjatrader.com',
    description: 'Futures and forex trading platform',
    priority: 70,
  },
  {
    name: 'Oanda',
    country: 'US',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.oanda.com',
    description: 'Forex and CFD trading',
    priority: 65,
  },
  {
    name: 'FXCM',
    country: 'UK',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.fxcm.com',
    description: 'Forex and CFD broker',
    priority: 65,
  },
  {
    name: 'IG Markets',
    displayName: 'IG Group',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.ig.com',
    description: 'Multi-asset CFD broker',
    priority: 65,
  },

  // ============================================================================
  // TIER 3 - PROP FIRMS (High Priority)
  // ============================================================================
  {
    name: 'FTMO',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX, BrokerAssetType.FUTURES],
    websiteUrl: 'https://ftmo.com',
    description: 'Leading forex prop trading firm',
    priority: 80,
  },
  {
    name: 'Apex Trader Funding',
    displayName: 'Apex Trader Funding (Rithmic)',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://apextraderfunding.com',
    csvTemplateUrl: '/docs/brokers/csv-formats/apex-rithmic.md',
    description: 'Futures prop trading firm using Rithmic platform - CSV export via R|Trader Pro',
    priority: 75,
  },
  {
    name: 'TopstepX',
    displayName: 'TopstepX (ProjectX API)',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.topsteptrader.com/topstepx/',
    apiDocumentationUrl: 'https://help.topstep.com/en/articles/11187768-topstepx-api-access',
    description: 'First prop firm with native API - Futures trading evaluation & funded accounts',
    priority: 88,
  },
  {
    name: 'The5ers',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://the5ers.com',
    description: 'Forex prop trading firm',
    priority: 70,
  },
  {
    name: 'Funded Next',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://fundednext.com',
    description: 'Forex prop trading firm',
    priority: 70,
  },

  // ============================================================================
  // US BROKERS
  // ============================================================================
  {
    name: 'E*TRADE',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://us.etrade.com',
    priority: 60,
  },
  {
    name: 'Fidelity',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.fidelity.com',
    priority: 60,
  },
  {
    name: 'Robinhood',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://robinhood.com',
    priority: 55,
  },
  {
    name: 'Webull',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.webull.com',
    priority: 55,
  },
  {
    name: 'Tastytrade',
    displayName: 'tastytrade (formerly tastyworks)',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://tastytrade.com',
    priority: 55,
  },
  {
    name: 'Think or Swim',
    displayName: 'thinkorswim by TD Ameritrade',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS, BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.tdameritrade.com/tools-and-platforms/thinkorswim.html',
    priority: 60,
  },
  {
    name: 'Lightspeed',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.lightspeed.com',
    priority: 50,
  },
  {
    name: 'Cobra Trading',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.cobratrading.com',
    priority: 45,
  },
  {
    name: 'SpeedTrader',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.speedtrader.com',
    priority: 45,
  },
  {
    name: 'Centerpoint Securities',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.centerpointsecurities.com',
    priority: 45,
  },

  // ============================================================================
  // EUROPEAN BROKERS
  // ============================================================================
  {
    name: 'Saxo Bank',
    country: 'DK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.home.saxo',
    priority: 60,
  },
  {
    name: 'Degiro',
    country: 'NL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.degiro.eu',
    priority: 55,
  },
  {
    name: 'Trading 212',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.trading212.com',
    priority: 55,
  },
  {
    name: 'eToro',
    country: 'CY',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.CRYPTO, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.etoro.com',
    priority: 55,
  },
  {
    name: 'Plus500',
    country: 'IL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.plus500.com',
    priority: 50,
  },
  {
    name: 'XTB',
    country: 'PL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.xtb.com',
    priority: 50,
  },
  {
    name: 'Swissquote',
    country: 'CH',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.swissquote.com',
    priority: 50,
  },
  {
    name: 'Admiral Markets',
    country: 'EE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://admiralmarkets.com',
    priority: 50,
  },
  {
    name: 'CMC Markets',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.cmcmarkets.com',
    priority: 50,
  },
  {
    name: 'Pepperstone',
    country: 'AU',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.pepperstone.com',
    priority: 50,
  },

  // ============================================================================
  // FOREX BROKERS
  // ============================================================================
  {
    name: 'IC Markets',
    country: 'AU',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.icmarkets.com',
    priority: 55,
  },
  {
    name: 'FP Markets',
    country: 'AU',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.fpmarkets.com',
    priority: 50,
  },
  {
    name: 'Forex.com',
    country: 'US',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.forex.com',
    priority: 55,
  },
  {
    name: 'FXTM',
    displayName: 'ForexTime (FXTM)',
    country: 'CY',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.forextime.com',
    priority: 45,
  },
  {
    name: 'HotForex',
    country: 'CY',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.hotforex.com',
    priority: 45,
  },
  {
    name: 'XM',
    country: 'CY',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.xm.com',
    priority: 50,
  },
  {
    name: 'FBS',
    country: 'BZ',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://fbs.com',
    priority: 45,
  },
  {
    name: 'Exness',
    country: 'CY',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.exness.com',
    priority: 50,
  },
  {
    name: 'Tickmill',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.tickmill.com',
    priority: 45,
  },
  {
    name: 'RoboForex',
    country: 'BZ',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.roboforex.com',
    priority: 45,
  },

  // ============================================================================
  // CRYPTO EXCHANGES
  // ============================================================================
  {
    name: 'Binance',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.binance.com',
    priority: 60,
  },
  {
    name: 'Coinbase',
    country: 'US',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.coinbase.com',
    priority: 60,
  },
  {
    name: 'Kraken',
    country: 'US',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.kraken.com',
    priority: 55,
  },
  {
    name: 'Bybit',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.bybit.com',
    priority: 55,
  },
  {
    name: 'OKX',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.okx.com',
    priority: 50,
  },
  {
    name: 'Bitfinex',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.bitfinex.com',
    priority: 50,
  },
  {
    name: 'KuCoin',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.kucoin.com',
    priority: 50,
  },
  {
    name: 'Gate.io',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.gate.io',
    priority: 45,
  },
  {
    name: 'Gemini',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.gemini.com',
    priority: 50,
  },
  {
    name: 'Bitstamp',
    country: 'LU',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.bitstamp.net',
    priority: 50,
  },

  // ============================================================================
  // FUTURES BROKERS
  // ============================================================================
  {
    name: 'AMP Futures',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.ampfutures.com',
    priority: 60,
  },
  {
    name: 'NinjaTrader Brokerage',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FUTURES],
    websiteUrl: 'https://ninjatrader.com/brokerage',
    priority: 55,
  },
  {
    name: 'Optimus Futures',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FUTURES],
    websiteUrl: 'https://optimusfutures.com',
    priority: 55,
  },
  {
    name: 'EdgeClear',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.edgeclear.com',
    priority: 50,
  },
  {
    name: 'Dorman Trading',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.dormantrading.com',
    priority: 50,
  },

  // ============================================================================
  // ADDITIONAL PROP FIRMS
  // ============================================================================
  {
    name: 'MyFundedFX',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://myfundedfx.com',
    priority: 65,
  },
  {
    name: 'FXIFY',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://fxify.com',
    priority: 60,
  },
  {
    name: 'True Forex Funds',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://trueforexfunds.com',
    priority: 60,
  },
  {
    name: 'Lux Trading Firm',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://luxtradingfirm.com',
    priority: 60,
  },
  {
    name: 'Earn2Trade',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://earn2trade.com',
    priority: 65,
  },
  {
    name: 'Bulenox',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://bulenox.com',
    priority: 55,
  },
  {
    name: 'Take Profit Trader',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://takeprofittrader.com',
    priority: 65,
  },
  {
    name: 'Uprofit',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://uprofit.com',
    priority: 55,
  },

  // ============================================================================
  // ASIAN BROKERS
  // ============================================================================
  {
    name: 'Rakuten Securities',
    country: 'JP',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.rakuten-sec.co.jp',
    priority: 45,
  },
  {
    name: 'SBI Securities',
    country: 'JP',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.sbisec.co.jp',
    priority: 45,
  },
  {
    name: 'Tiger Brokers',
    country: 'SG',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.tigerbrokers.com',
    priority: 50,
  },
  {
    name: 'Futu',
    displayName: 'Futu (moomoo)',
    country: 'HK',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.futunn.com',
    priority: 50,
  },
  {
    name: 'Zerodha',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://zerodha.com',
    priority: 50,
  },
  {
    name: 'Upstox',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://upstox.com',
    priority: 45,
  },

  // ============================================================================
  // CANADIAN BROKERS
  // ============================================================================
  {
    name: 'Questrade',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.questrade.com',
    priority: 55,
  },
  {
    name: 'Wealthsimple',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.wealthsimple.com',
    priority: 50,
  },
  {
    name: 'Interactive Brokers Canada',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.interactivebrokers.ca',
    priority: 60,
  },

  // ============================================================================
  // AUSTRALIAN BROKERS
  // ============================================================================
  {
    name: 'CommSec',
    displayName: 'CommSec (Commonwealth Bank)',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.commsec.com.au',
    priority: 45,
  },
  {
    name: 'Stake',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://hellostake.com',
    priority: 50,
  },
  {
    name: 'SelfWealth',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.selfwealth.com.au',
    priority: 45,
  },

  // ============================================================================
  // LATIN AMERICAN BROKERS
  // ============================================================================
  {
    name: 'XP Investimentos',
    country: 'BR',
    region: 'Latin America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.xpi.com.br',
    priority: 40,
  },
  {
    name: 'Clear',
    country: 'BR',
    region: 'Latin America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.clear.com.br',
    priority: 40,
  },
  {
    name: 'Rico',
    country: 'BR',
    region: 'Latin America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.rico.com.vc',
    priority: 40,
  },

  // ============================================================================
  // ADDITIONAL EUROPEAN BROKERS
  // ============================================================================
  {
    name: 'Scalable Capital',
    country: 'DE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://scalable.capital',
    priority: 50,
  },
  {
    name: 'Trade Republic',
    country: 'DE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://traderepublic.com',
    priority: 50,
  },
  {
    name: 'Flatex',
    country: 'DE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.flatex.de',
    priority: 45,
  },
  {
    name: 'Revolut',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.revolut.com',
    priority: 50,
  },
  {
    name: 'Freetrade',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://freetrade.io',
    priority: 45,
  },
  {
    name: 'Hargreaves Lansdown',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.hl.co.uk',
    priority: 50,
  },

  // ============================================================================
  // ADDITIONAL FOREX BROKERS (Continuing to 240+)
  // ============================================================================
  {
    name: 'AvaTrade',
    country: 'IE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.avatrade.com',
    priority: 45,
  },
  {
    name: 'FxPro',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.fxpro.com',
    priority: 45,
  },
  {
    name: 'ThinkMarkets',
    country: 'AU',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.thinkmarkets.com',
    priority: 45,
  },
  {
    name: 'Vantage',
    displayName: 'Vantage Markets',
    country: 'AU',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.vantagemarkets.com',
    priority: 45,
  },
  {
    name: 'Eightcap',
    country: 'AU',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.eightcap.com',
    priority: 45,
  },
  {
    name: 'BlackBull Markets',
    country: 'NZ',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.blackbull.com',
    priority: 45,
  },
  {
    name: 'GO Markets',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.gomarkets.com',
    priority: 40,
  },
  {
    name: 'Fusion Markets',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.fusionmarkets.com',
    priority: 45,
  },
  {
    name: 'Axi',
    displayName: 'Axi (formerly AxiTrader)',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.axi.com',
    priority: 45,
  },
  {
    name: 'Global Prime',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.globalprime.com',
    priority: 40,
  },

  // ============================================================================
  // MORE PROP FIRMS (Continuing expansion)
  // ============================================================================
  {
    name: 'SurgeTrader',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://surgetrader.com',
    priority: 60,
  },
  {
    name: 'Funded Trading Plus',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://fundedtradingplus.com',
    priority: 60,
  },
  {
    name: 'The Funded Trader',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://thefundedtraderprogram.com',
    priority: 60,
  },
  {
    name: 'Blue Guardian',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://blueguardian.com',
    priority: 55,
  },
  {
    name: 'Tradeify',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://tradeify.com',
    priority: 60,
  },
  {
    name: 'City Traders Imperium',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://citytraders.com',
    priority: 60,
  },
  {
    name: 'Funding Pips',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://fundingpips.com',
    priority: 55,
  },
  {
    name: 'Fast Track Trading',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://fasttracktrading.com',
    priority: 55,
  },
  {
    name: 'E8 Funding',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://e8funding.com',
    priority: 60,
  },
  {
    name: 'Goat Funded Trader',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://goatfundedtrader.com',
    priority: 55,
  },

  // ============================================================================
  // MORE US BROKERS
  // ============================================================================
  {
    name: 'Merrill Edge',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.merrilledge.com',
    priority: 50,
  },
  {
    name: 'Ally Invest',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.ally.com/invest',
    priority: 50,
  },
  {
    name: 'Vanguard',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://investor.vanguard.com',
    priority: 50,
  },
  {
    name: 'Schwab',
    displayName: 'Charles Schwab',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS, BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.schwab.com',
    priority: 60,
  },
  {
    name: 'Firstrade',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.firstrade.com',
    priority: 45,
  },
  {
    name: 'Public',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://public.com',
    priority: 45,
  },
  {
    name: 'SoFi Invest',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.sofi.com/invest',
    priority: 45,
  },
  {
    name: 'Moomoo',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.moomoo.com',
    priority: 50,
  },

  // ============================================================================
  // MORE CRYPTO EXCHANGES
  // ============================================================================
  {
    name: 'Crypto.com',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://crypto.com',
    priority: 50,
  },
  {
    name: 'Huobi',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.huobi.com',
    priority: 45,
  },
  {
    name: 'Bitget',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.bitget.com',
    priority: 45,
  },
  {
    name: 'MEXC',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.mexc.com',
    priority: 45,
  },
  {
    name: 'Phemex',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://phemex.com',
    priority: 40,
  },
  {
    name: 'Deribit',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.deribit.com',
    priority: 45,
  },
  {
    name: 'BitMEX',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.bitmex.com',
    priority: 45,
  },
  {
    name: 'Poloniex',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://poloniex.com',
    priority: 40,
  },

  // ============================================================================
  // ADDITIONAL INTERNATIONAL BROKERS
  // ============================================================================
  {
    name: 'BUX',
    country: 'NL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://getbux.com',
    priority: 40,
  },
  {
    name: 'Bux Zero',
    country: 'NL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://getbux.com/bux-zero',
    priority: 40,
  },
  {
    name: 'Nordnet',
    country: 'SE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.nordnet.se',
    priority: 45,
  },
  {
    name: 'Avanza',
    country: 'SE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.avanza.se',
    priority: 40,
  },
  {
    name: 'Lynx',
    country: 'NL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.lynx.nl',
    priority: 45,
  },
  {
    name: 'Tastyworks',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.tastyworks.com',
    priority: 50,
  },
  {
    name: 'Just2Trade',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.just2trade.com',
    priority: 40,
  },
  {
    name: 'TradeZero',
    country: 'BS',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.tradezero.com',
    priority: 45,
  },
  {
    name: 'CMEG',
    displayName: 'CMEG (Capital Markets Elite Group)',
    country: 'BS',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.cmegtrading.com',
    priority: 40,
  },
  {
    name: 'Choice',
    displayName: 'Choice Trade',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS, BrokerAssetType.OPTIONS],
    websiteUrl: 'https://www.choicetrade.com',
    priority: 40,
  },

  // ============================================================================
  // MORE ASIAN BROKERS
  // ============================================================================
  {
    name: 'POEMS',
    displayName: 'Phillip Securities (POEMS)',
    country: 'SG',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.poems.com.sg',
    priority: 40,
  },
  {
    name: 'DBS Vickers',
    country: 'SG',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.dbsvickers.com',
    priority: 40,
  },
  {
    name: 'OCBC Securities',
    country: 'SG',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.ocbcsec.com',
    priority: 40,
  },
  {
    name: 'Angel One',
    displayName: 'Angel One (formerly Angel Broking)',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.angelone.in',
    priority: 45,
  },
  {
    name: '5paisa',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.5paisa.com',
    priority: 40,
  },
  {
    name: 'Groww',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://groww.in',
    priority: 45,
  },
  {
    name: 'ICICI Direct',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.icicidirect.com',
    priority: 40,
  },
  {
    name: 'HDFC Securities',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.hdfcsec.com',
    priority: 40,
  },
  {
    name: 'Kotak Securities',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.kotaksecurities.com',
    priority: 40,
  },
  {
    name: 'Sharekhan',
    country: 'IN',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.sharekhan.com',
    priority: 40,
  },

  // ============================================================================
  // MORE EUROPEAN BROKERS
  // ============================================================================
  {
    name: 'Boursorama',
    country: 'FR',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.boursorama.com',
    priority: 40,
  },
  {
    name: 'Fortuneo',
    country: 'FR',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.fortuneo.fr',
    priority: 40,
  },
  {
    name: 'Bourse Direct',
    country: 'FR',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.boursedirect.fr',
    priority: 40,
  },
  {
    name: 'Binck',
    country: 'NL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.binck.nl',
    priority: 40,
  },
  {
    name: 'Consorsbank',
    country: 'DE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.consorsbank.de',
    priority: 40,
  },
  {
    name: 'Comdirect',
    country: 'DE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.comdirect.de',
    priority: 40,
  },
  {
    name: 'OnVista Bank',
    country: 'DE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.onvista-bank.de',
    priority: 35,
  },
  {
    name: 'ING',
    displayName: 'ING DiBa',
    country: 'DE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.ing.de',
    priority: 40,
  },
  {
    name: 'Keytrade Bank',
    country: 'BE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.keytradebank.be',
    priority: 35,
  },
  {
    name: 'Bolero',
    country: 'BE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.bolero.be',
    priority: 35,
  },

  // ============================================================================
  // MORE FOREX & CFD BROKERS
  // ============================================================================
  {
    name: 'Markets.com',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.markets.com',
    priority: 45,
  },
  {
    name: 'Capital.com',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://capital.com',
    priority: 45,
  },
  {
    name: 'Spreadex',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.spreadex.com',
    priority: 40,
  },
  {
    name: 'City Index',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.cityindex.com',
    priority: 45,
  },
  {
    name: 'FOREX.com',
    country: 'US',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.forex.com',
    priority: 50,
  },
  {
    name: 'GAIN Capital',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.gaincapital.com',
    priority: 40,
  },
  {
    name: 'Dukascopy',
    country: 'CH',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.dukascopy.com',
    priority: 45,
  },
  {
    name: 'Darwinex',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.darwinex.com',
    priority: 45,
  },
  {
    name: 'LMAX',
    displayName: 'LMAX Exchange',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.lmax.com',
    priority: 40,
  },
  {
    name: 'ActivTrades',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.activtrades.com',
    priority: 45,
  },

  // ============================================================================
  // ADDITIONAL PROP FIRMS (Reaching 240+)
  // ============================================================================
  {
    name: 'Alpha Capital Group',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://alphacapitalgroup.io',
    priority: 55,
  },
  {
    name: 'Fidelcrest',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://www.fidelcrest.com',
    priority: 60,
  },
  {
    name: 'Smart Prop Trader',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://smartproptrader.com',
    priority: 55,
  },
  {
    name: 'Audacity Capital',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.audacitycapital.co.uk',
    priority: 55,
  },
  {
    name: 'OneUp Trader',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://oneuptrader.com',
    priority: 60,
  },
  {
    name: 'Maverick Trading',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.mavericktrading.com',
    priority: 55,
  },
  {
    name: 'T3 Trading',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.t3trading.com',
    priority: 55,
  },
  {
    name: 'Bright Trading',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.stocktrading.com',
    priority: 55,
  },
  {
    name: 'SMB Capital',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.smbcap.com',
    priority: 55,
  },
  {
    name: 'Maverick FX',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FOREX],
    websiteUrl: 'https://maverickfx.net',
    priority: 50,
  },

  // ============================================================================
  // FINAL ADDITIONS TO REACH 240+
  // ============================================================================
  {
    name: 'Moneta Markets',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.monetamarkets.com',
    priority: 40,
  },
  {
    name: 'FXOpen',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.fxopen.com',
    priority: 45,
  },
  {
    name: 'FXChoice',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.fxchoice.com',
    priority: 40,
  },
  {
    name: 'FXGlory',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.fxglory.com',
    priority: 35,
  },
  {
    name: 'InstaForex',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.instaforex.com',
    priority: 40,
  },
  {
    name: 'LiteForex',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.liteforex.com',
    priority: 35,
  },
  {
    name: 'NordFX',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://nordfx.com',
    priority: 35,
  },
  {
    name: 'OctaFX',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.octafx.com',
    priority: 40,
  },
  {
    name: 'Weltrade',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://weltrade.com',
    priority: 35,
  },
  {
    name: 'Windsor Brokers',
    country: 'CY',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.windsorbrokers.com',
    priority: 35,
  },
  {
    name: 'AAAFx',
    country: 'GR',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.aaafx.com',
    priority: 35,
  },
  {
    name: 'Atiora',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.atiora.com',
    priority: 30,
  },
  {
    name: 'Axiory',
    country: 'BZ',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.axiory.com',
    priority: 45,
  },
  {
    name: 'FXDD',
    country: 'MT',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.fxdd.com',
    priority: 40,
  },
  {
    name: 'FXPIG',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.fxpig.com',
    priority: 35,
  },
  {
    name: 'HFM',
    displayName: 'HF Markets (HotForex)',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.hfm.com',
    priority: 45,
  },
  {
    name: 'IronFX',
    country: 'CY',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://www.ironfx.com',
    priority: 35,
  },
  {
    name: 'JustMarkets',
    region: 'Global',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX],
    websiteUrl: 'https://justmarkets.com',
    priority: 35,
  },
  {
    name: 'LCG',
    displayName: 'London Capital Group',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.lcg.com',
    priority: 40,
  },
  {
    name: 'Libertex',
    region: 'Global',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.FOREX, BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.libertex.com',
    priority: 45,
  },

  // ============================================================================
  // ADDITIONAL BROKERS FROM COMPILATION (Reaching 250+)
  // ============================================================================
  
  // More US Brokers
  {
    name: 'Zacks Trade',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.zackstrade.com',
    priority: 45,
  },
  {
    name: 'M1 Finance',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.m1finance.com',
    priority: 45,
  },
  {
    name: 'Tradier',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://tradier.com',
    description: 'API-first brokerage platform',
    priority: 75,
  },

  // UK Brokers
  {
    name: 'AJ Bell',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.ajbell.co.uk',
    priority: 50,
  },
  {
    name: 'Interactive Investor',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.ii.co.uk',
    priority: 50,
  },
  {
    name: 'Fineco Bank UK',
    country: 'UK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://finecobank.co.uk',
    priority: 45,
  },

  // More Prop Firms
  {
    name: 'MyFundedFutures',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.myfundedfutures.com',
    priority: 65,
  },
  {
    name: 'Leeloo Trading',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://leelootrading.com',
    priority: 60,
  },
  {
    name: 'TradeDay',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://www.tradeday.com',
    priority: 60,
  },
  {
    name: 'Elite Trader Funding',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.PROP_FIRM, BrokerAssetType.FUTURES],
    websiteUrl: 'https://elitetraderfunding.com',
    priority: 60,
  },

  // European Brokers
  {
    name: 'Smartbroker',
    country: 'DE',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.smartbroker.de',
    priority: 45,
  },
  {
    name: 'BforBank',
    country: 'FR',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.bforbank.com',
    priority: 40,
  },
  {
    name: 'Directa',
    country: 'IT',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.directa.it',
    priority: 45,
  },
  {
    name: 'Fineco Bank',
    country: 'IT',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://finecobank.com',
    priority: 50,
  },
  {
    name: 'Webank',
    country: 'IT',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.webank.it',
    priority: 40,
  },
  {
    name: 'IWBank',
    country: 'IT',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.iwbank.it',
    priority: 40,
  },
  {
    name: 'mBank',
    country: 'PL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.mbank.pl',
    priority: 40,
  },
  {
    name: 'Bossa',
    country: 'PL',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://bossa.pl',
    priority: 40,
  },
  {
    name: 'Nordea',
    country: 'FI',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.nordea.com',
    priority: 40,
  },
  {
    name: 'DNB Markets',
    country: 'NO',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.dnb.no',
    priority: 40,
  },
  {
    name: 'Saxo Bank Denmark',
    country: 'DK',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.home.saxo/dk',
    priority: 50,
  },
  {
    name: 'Renta 4',
    country: 'ES',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.r4.com',
    priority: 45,
  },
  {
    name: 'Selfbank',
    country: 'ES',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.selfbank.es',
    priority: 40,
  },
  {
    name: 'Openbank',
    country: 'ES',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.openbank.es',
    priority: 40,
  },
  {
    name: 'ClickTrade',
    country: 'ES',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.clicktrade.es',
    priority: 40,
  },
  {
    name: 'Cornertrader',
    country: 'CH',
    region: 'Europe',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.cornertrader.ch',
    priority: 45,
  },
  {
    name: 'PostFinance',
    country: 'CH',
    region: 'Europe',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.postfinance.ch',
    priority: 40,
  },

  // Australian Brokers
  {
    name: 'NAB Trade',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.nabtrade.com.au',
    priority: 45,
  },
  {
    name: 'Westpac Trading',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.westpac.com.au',
    priority: 40,
  },
  {
    name: 'ANZ Share Investing',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.anz.com.au',
    priority: 40,
  },
  {
    name: 'Superhero',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://superhero.com.au',
    priority: 45,
  },
  {
    name: 'CMC Markets Australia',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.cmcmarkets.com/en-au',
    priority: 50,
  },
  {
    name: 'IG Australia',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.ig.com/au',
    priority: 50,
  },

  // Singapore Brokers
  {
    name: 'Saxo Markets Singapore',
    country: 'SG',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.home.saxo/sg',
    priority: 50,
  },
  {
    name: 'Moomoo Singapore',
    country: 'SG',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.moomoo.com/sg',
    priority: 50,
  },
  {
    name: 'FSMOne',
    country: 'SG',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.fsmone.com.sg',
    priority: 40,
  },

  // Hong Kong Brokers
  {
    name: 'Futu Securities',
    country: 'HK',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.futunn.com',
    priority: 50,
  },
  {
    name: 'Tiger Brokers HK',
    country: 'HK',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.tigerbrokers.com.hk',
    priority: 50,
  },
  {
    name: 'Interactive Brokers HK',
    country: 'HK',
    region: 'Asia',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.interactivebrokers.com.hk',
    priority: 70,
  },
  {
    name: 'Saxo Markets HK',
    country: 'HK',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.MULTI_ASSET],
    websiteUrl: 'https://www.home.saxo/hk',
    priority: 50,
  },
  {
    name: 'HSBC InvestDirect',
    country: 'HK',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.hsbc.com.hk/investments',
    priority: 40,
  },
  {
    name: 'Standard Chartered HK',
    country: 'HK',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.sc.com/hk',
    priority: 40,
  },

  // Japanese Brokers
  {
    name: 'Monex',
    country: 'JP',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.monex.co.jp',
    priority: 40,
  },
  {
    name: 'Matsui Securities',
    country: 'JP',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.matsui.co.jp',
    priority: 40,
  },
  {
    name: 'GMO Click Securities',
    country: 'JP',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.click-sec.com',
    priority: 40,
  },

  // South Korean Brokers
  {
    name: 'Mirae Asset',
    country: 'KR',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.miraeasset.com',
    priority: 40,
  },
  {
    name: 'KB Securities',
    country: 'KR',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.kbsec.com',
    priority: 40,
  },
  {
    name: 'Samsung Securities',
    country: 'KR',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.samsungpop.com',
    priority: 40,
  },

  // Canadian Brokers
  {
    name: 'TD Direct Investing',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.td.com/ca/direct-investing',
    priority: 50,
  },
  {
    name: 'RBC Direct Investing',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.rbcdirectinvesting.com',
    priority: 50,
  },
  {
    name: 'Scotia iTRADE',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.scotiaitrade.com',
    priority: 50,
  },
  {
    name: 'BMO InvestorLine',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.bmo.com/main/personal/investments/online-investing',
    priority: 50,
  },
  {
    name: 'CIBC Investor\'s Edge',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.cibc.com/en/personal-banking/investments/invest-online.html',
    priority: 50,
  },
  {
    name: 'National Bank Direct Brokerage',
    country: 'CA',
    region: 'North America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.STOCKS],
    websiteUrl: 'https://www.nbc.ca/personal/investments/direct-brokerage.html',
    priority: 50,
  },

  // More Crypto Exchanges
  {
    name: 'Upbit',
    country: 'KR',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://upbit.com',
    priority: 50,
  },
  {
    name: 'Bithumb',
    country: 'KR',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.bithumb.com',
    priority: 50,
  },
  {
    name: 'Korbit',
    country: 'KR',
    region: 'Asia',
    integrationStatus: IntegrationStatus.COMING_SOON,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.korbit.co.kr',
    priority: 40,
  },
  {
    name: 'Coincheck',
    country: 'JP',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://coincheck.com',
    priority: 45,
  },
  {
    name: 'bitFlyer',
    country: 'JP',
    region: 'Asia',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://bitflyer.com',
    priority: 45,
  },
  {
    name: 'Bitso',
    country: 'MX',
    region: 'Latin America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://bitso.com',
    priority: 45,
  },
  {
    name: 'Mercado Bitcoin',
    country: 'BR',
    region: 'Latin America',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.mercadobitcoin.com.br',
    priority: 45,
  },
  {
    name: 'Luno',
    country: 'UK',
    region: 'Global',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.luno.com',
    priority: 45,
  },
  {
    name: 'Independent Reserve',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.independentreserve.com',
    priority: 45,
  },
  {
    name: 'CoinSpot',
    country: 'AU',
    region: 'Asia-Pacific',
    integrationStatus: IntegrationStatus.FILE_UPLOAD,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://www.coinspot.com.au',
    priority: 45,
  },
  {
    name: 'Bittrex',
    country: 'US',
    region: 'North America',
    integrationStatus: IntegrationStatus.API,
    supportedAssets: [BrokerAssetType.CRYPTO],
    websiteUrl: 'https://bittrex.com',
    priority: 45,
  },
];

async function main() {
  console.log('🌱 Starting broker database seed...');
  console.log(`📊 Total brokers to seed: ${brokers.length}`);

  let created = 0;
  let skipped = 0;
  let errors = 0;

  for (const broker of brokers) {
    try {
      // Set isActive to true only for brokers with API integration
      const isActive = broker.integrationStatus === IntegrationStatus.API;
      
      await prisma.broker.upsert({
        where: { name: broker.name },
        update: {
          displayName: broker.displayName,
          country: broker.country,
          region: broker.region,
          integrationStatus: broker.integrationStatus,
          supportedAssets: broker.supportedAssets,
          logoUrl: broker.logoUrl,
          websiteUrl: broker.websiteUrl,
          apiDocumentationUrl: broker.apiDocumentationUrl,
          csvTemplateUrl: broker.csvTemplateUrl,
          description: broker.description,
          priority: broker.priority,
          isActive: isActive,
        },
        create: {
          ...broker,
          isActive: isActive,
        },
      });
      created++;
      if (created % 50 === 0) {
        console.log(`✅ Seeded ${created} brokers...`);
      }
    } catch (error) {
      console.error(`❌ Error seeding broker ${broker.name}:`, error);
      errors++;
    }
  }

  console.log('\n📈 Seed Summary:');
  console.log(`✅ Created/Updated: ${created}`);
  console.log(`⏭️  Skipped: ${skipped}`);
  console.log(`❌ Errors: ${errors}`);

  // Stats by integration status
  const stats = await prisma.broker.groupBy({
    by: ['integrationStatus'],
    _count: true,
  });

  console.log('\n📊 Brokers by Integration Status:');
  stats.forEach((stat) => {
    console.log(`  ${stat.integrationStatus}: ${stat._count}`);
  });

  // Stats by region
  const regionStats = await prisma.broker.groupBy({
    by: ['region'],
    _count: true,
    orderBy: {
      _count: {
        region: 'desc',
      },
    },
  });

  console.log('\n🌍 Brokers by Region:');
  regionStats.forEach((stat) => {
    console.log(`  ${stat.region || 'Unknown'}: ${stat._count}`);
  });

  console.log('\n✅ Broker database seed completed!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
